apiVersion: v1
kind: Service
metadata:
  name: admessage
spec:
  type: NodePort
  selector:
    app: admessage
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  externalTrafficPolicy: Local
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: admessage
spec:
  serviceName: "admessage"
  replicas: 1
  selector:
    matchLabels:
      app: admessage
  template:
    metadata:
      labels:
        app: admessage
    spec:
      containers:
      - name: wstore
        image:  iad.ocir.io/axfo51x8x2ap/devlive-admessage:latest
        command: ["java", "-jar", "./AdMessage.jar", "--server.port=8082"]
        ports:
        - containerPort: 8083
        env:
          - name: spring.datasource.url
            value: jdbc:mysql://<mds-private-ip-address>/wine
          - name: spring.datasource.username
            value: wine
          - name: spring.datasource.password
            value: O&Mdemo1
